# Generated by Django 5.2.4 on 2026-08-11 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climateapp', '0002_weatherstation_weatherreading'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('rainfall', models.FloatField()),
                ('air_quality', models.FloatField()),
                ('recorded_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='weatherstation',
            name='region',
        ),
        migrations.RemoveField(
            model_name='weatherreading',
            name='station',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='WeatherReading',
        ),
        migrations.DeleteModel(
            name='WeatherStation',
        ),
    ]
